apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name.api }}
  annotations:
   ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{ .Values.app.host }}
    http:
      paths:
        - path: /api 
          backend:
            serviceName: http
            servicePort: {{ .Values.port.api }}
        - path: /socket.io
          backend:
            serviceName: ws
            servicePort: {{ .Values.port.ws }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name.ui }}
  annotations:
   ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{ .Values.app.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: http
            servicePort: 80
